### ISSUE TITLE
Bulbs

### ISSUE THREAD

**Issue by mlhomeboy** [kpsuperplane/homebridge-wiz-lan#42]
This plug in was working fine a month ago, now since some updates the bulbs are not appearing in accessories. I have uninstalled the plug-in multiple times.

Any advise on troubleshooting?

Thanks

-Mike

**Comment by prattson** [comment]
My Wiz bulb also disappeared from my list of accessories when I updated the plugin to version 3.0. Reinstalling version 2.2.0 brought it back.

I tried using the full configuration suggested by Kevin on the homebridge-wiz-lan GitHub page to get the bulb to reappear in version 3.0, but I didn't have any joy. That said, my knowledge of JSON is almost non-existent and my understanding of networking in general isn't much better, so I could easily have missed something important. I would be interested to know what's going wrong, but at least I have a fallback with version 2.2.0. Hope that works for you as well.

**Comment by mlhomeboy** [comment]
Thanks
I just tried rolling back to version 2.2.0 but still no luck. :(

**Comment by kpsuperplane** [comment]
@prattson @mlhomeboy can I ask what kind of bulbs y'all have that aren't showing up?

**Comment by mlhomeboy** [comment]
The ones from Home Depot; i will pull one down to get the model if it would help.

**Comment by kpsuperplane** [comment]
@mlhomeboy one thing you can try is manually adding the missing bulb's IP address to the config as seen on the read me. You can find the IP address in the wiz app settings tab like so:
![image](https://user-images.githubusercontent.com/4126319/109711312-95c2b680-7b53-11eb-9559-2eaf572169ee.jpeg)
![image](https://user-images.githubusercontent.com/4126319/109711331-9a876a80-7b53-11eb-9995-8a7401a0af0b.jpeg)
![image](https://user-images.githubusercontent.com/4126319/109711285-8d6a7b80-7b53-11eb-85fe-15035019cc00.jpeg)
![image](https://user-images.githubusercontent.com/4126319/109711343-9ce9c480-7b53-11eb-9c43-e3d94066dc6f.png)

**Comment by prattson** [comment]
I just have one WIZ bulb: A19 Colors (Version 1.21.2, model 23007 according to the app).

Cheers,

m a r t i n

**Comment by kpsuperplane** [comment]
@prattson  can you also try the solution above?

**Comment by kpsuperplane** [comment]
For the example above your config would look something like this:

```
{
  "platform": "WizSmarthome",
  "name": "Wiz",
  "devices": [
      { "host": "192.168.1.234" }
   ]
}
```

**Comment by mlhomeboy** [comment]
I have the bulb ip in the JSON Config - still nothing..

{
            "platform": "WizSmarthome",
            "name": "WizSmarthome",
            "port": "38900",
            "broadcast": "255.255.255.0",
            "address": "192.168.0.225",
            "devices": [
                {
                    "host": "192.168.0.198"
                },
                {
                    "host": "192.168.0.172"
                },
                {
                    "host": "192.168.0.254"

**Comment by kpsuperplane** [comment]
@mlhomeboy unfortunately that means something is misconfigured in your network and your server is unable to communicate with the bulbs. If I had to guess, either
a) Your broadcast or address config is incorrect
b) The non-responding bulbs are firewalled off from your server for some reason

**Comment by prattson** [comment]
Thanks. Since my bulb appears to be working fine with version 2.2.0, I think I’m just going to leave it for now. If  I pluck up the courage to try updating again, I’ll let you know what happens!

m a r t i n

**Comment by mlhomeboy** [comment]
Everything thing is on the same no firewall in between; as stated it was working fine then i updated and it stopped working.

**Comment by mlhomeboy** [comment]
> @mlhomeboy unfortunately that means something is misconfigured in your network and your server is unable to communicate with the bulbs. If I had to guess, either
> a) Your broadcast or address config is incorrect
> b) The non-responding bulbs are firewalled off from your server for some reason

**Comment by mlhomeboy** [comment]
Well Im happy to say this is now working - IT WAS NOT THE NETWORK. Sorry I am a network manager and I hear that commit everyday. There is a setting in the wiz app that needs to be toggled. This should be added to the install instructions to have more happier clients.

![IMG_0402](https://user-images.githubusercontent.com/72017796/109963247-2fa47380-7cba-11eb-8f5b-f3c280a9fc47.jpeg)
