### ISSUE TITLE
Unable to control bulbs from Homekit

### ISSUE THREAD

**Issue by thesickkness** [kpsuperplane/homebridge-wiz-lan#6]
Starting on/about 14 July, about half of my bulbs (9ish) no longer respond to Homekit control via this plugin. Still working through the (new) Wiz app. Mix of A19 bulbs and recessed downlights, all RGB.

Updated npm/node.js.

All bulbs on same subnet.

I wonder if the app update changed something. I had to download a whole new one and migrate all of the configuration to it.

Anyone else having similar issue?

**Comment by dotkrnl** [comment]
I am still able to control the bulbs by manually sending UDP broadcast:

```
echo '{"method":"setPilot","env":"pro","params":{"mac":"[mac address]","src":"udp","state":true,"temp":2869,"dimming":100}}' | socat - UDP-DATAGRAM:255.255.255.255:38899,broadcast
```

I am looking into the source code and trying to figure out what went wrong.

**Comment by dotkrnl** [comment]
It seems that a recent upgrade requires the JSON sent to the bulb to be without: `"sceneId":0,"c":0,"w":0`.  With these parameters, the bulb will return `Invalid params`.  Removing it from `setPilot` in `lib/client/index.js` makes it work.

**Comment by Judas2016** [comment]
I can confirm that removing the parameter mentioned by dotkrnl solves my problem of bulbs not responding since latest firmware update.

**Comment by Judas2016** [comment]
> It seems that a recent upgrade requires the JSON sent to the bulb to be without: `"sceneId":0,"c":0,"w":0`. With these parameters, the bulb will return `Invalid params`. Removing it from `setPilot` in `lib/client/index.js` makes it work.

I can confirm this fixed the problem w/the latest Wiz firmware.

**Comment by eshventures** [comment]
For some of us novice users who are using HOOBS. Can we get an update to the plugin or can you please advise the JSON code we should enter into the configuration? I tried entering the set pilot code into hoobs configuration, but it kept saying “ Unable to save.
Please fix the following errors.

Invalid JSON in an platform.“ 

I assume I have the wrong syntax....any help would be appreciated. Thanks!

**Comment by kpsuperplane** [comment]
Hi @eshventures, I just merged the PR graciously submitted by @dotkrnl . Can you try updating to version 2.0.5?

**Comment by MB72430** [comment]
I am still having the same problem, the light bulbs don't react to any controls on the home app. The only way of controlling them is via the Wiz app. I've updated the plugin and still the same.

Any thoughts?

**Comment by eshventures** [comment]
> Hi @eshventures, I just merged the PR graciously submitted by @dotkrnl . Can you try updating to version 2.0.5?

@kpsuperplane - thanks so much I update to 2.0.5 and it’s working. Really appreciate your help along with @dotkrnl ’s. Thanks again!

**Comment by Judas2016** [comment]
> Hi @eshventures, I just merged the PR graciously submitted by @dotkrnl . Can you try updating to version 2.0.5?

I have upgraded to v2.05 and can confirm it's fixed the problem.

**Comment by kurtifier** [comment]
Hi I am fairly new to home bridge and I am having a little trouble setting this plugin up. I keep getting an error WizSmartHome was not registered by any plugin (see picture below). I am not sure what I did wrong. I installed using npm install -g homebridge-wiz-lan then added the necessary config seen in the second picture. Any help would be much appreciated
![light](https://user-images.githubusercontent.com/68803667/88743589-e70c5280-d0f9-11ea-9641-d1a7f788a3cb.PNG)
![log](https://user-images.githubusercontent.com/68803667/88743592-e7a4e900-d0f9-11ea-89a5-0f45f39e6178.PNG)

**Comment by Polishdad5** [comment]
I am having this exact issue. I have updated to v2.05 with no luck. Any other ideas?

**Comment by rk3rr** [comment]
I cannot seem to find the path to fix the issue with the plugin. Can someone help me out and let me know exactly how to get there? 
This is what was posted but I cannot find the file to edit **_It seems that a recent upgrade requires the JSON sent to the bulb to be without: "scene Id":0,"c":0,"w":0. With these parameters, the bulb will return Invalid params. Removing it from setPilot in lib/client/index.js makes it work._**
